export const ALL_MEDICINE_REQUEST = "ALL_MEDICINE_REQUEST";
export const ALL_MEDICINE_SUCCESS = "ALL_MEDICINE_SUCCESS";
export const ALL_MEDICINE_FAIL = "ALL_MEDICINE_FAIL";

export const MEDICINE_DETAILS_REQUEST = "MEDICINE_DETAILS_REQUEST";
export const MEDICINE_DETAILS_SUCCESS = "MEDICINE_DETAILS_SUCCESS";
export const MEDICINE_DETAILS_FAIL = "MEDICINE_DETAILS_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
