export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_ADMIN_REQUEST = "LOAD_ADMIN_REQUEST";
export const LOAD_ADMIN_SUCCESS = "LOAD_ADMIN_SUCCESS";
export const LOAD_ADMIN_FAIL = "LOAD_ADMIN_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
